Web/ForumSystem.Web/Controllers/CategoriesController.cs
namespace ForumSystem.Web.Controllers
{
    using System;

    using ForumSystem.Services.Data;
    using ForumSystem.Web.ViewModels.Categories;
    using ForumSystem.Web.ViewModels.Home;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    public class CategoriesController : Controller
    {
        private const int ItemsPerPage = 5;

        private readonly ICategoriesService categoriesService;
        private readonly IPostsService postsService;

        public CategoriesController(
            ICategoriesService categoriesService,
            IPostsService postsService)
        {
            this.categoriesService = categoriesService;
            this.postsService = postsService;
        }

        public IActionResult ByName(string name, int page = 1)
        {
            var viewModel = this.categoriesService.GetByName<CategoryViewModel>(name);

            viewModel.ForumPosts = this.postsService
                .GetByCategoryId<PostInCategoryViewModel>(viewModel.Id, ItemsPerPage, (page - 1) * ItemsPerPage);

            var count = this.postsService.GetCountByCategoryId(viewModel.Id);

            viewModel.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

            if (viewModel.PagesCount == 0)
            {
                viewModel.PagesCount = 1;
            }

            viewModel.CurrentPage = page;

            return this.View(viewModel);
        }

        public IActionResult All()
        {
            var viewModel = new IndexViewModel();
            var categories = this.categoriesService.GetAll<IndexCategoryViewModel>();
            viewModel.Categories = categories;

            return this.View(viewModel);
        }
    }
}

Web/ForumSystem.Web/Controllers/PostsController.cs
namespace ForumSystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using CloudinaryDotNet;
    using ForumSystem.Data.Models;
    using ForumSystem.Services.Data;
    using ForumSystem.Services.Mapping;
    using ForumSystem.Web.ViewModels.Posts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class PostsController : Controller
    {
        private const int ItemsPerPage = 5;
        private readonly IPostsService postsService;
        private readonly ICategoriesService categoriesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly Cloudinary cloudinary;

        public PostsController(
            IPostsService postsService,
            ICategoriesService categoriesService,
            UserManager<ApplicationUser> userManager,
            Cloudinary cloudinary)
        {
            this.postsService = postsService;
            this.categoriesService = categoriesService;
            this.userManager = userManager;
            this.cloudinary = cloudinary;
        }

        public IActionResult All(int page = 1, string search = null)
        {
            var viewmodel = new PostAllModel();
            viewmodel.Posts = this.postsService.GetAll<PostViewModel>(search, ItemsPerPage, (page - 1) * ItemsPerPage);
            var count = this.postsService.GetCount();
            viewmodel.Search = search;
            viewmodel.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

            if (viewmodel.PagesCount == 0)
            {
                viewmodel.PagesCount = 1;
            }

            viewmodel.CurrentPage = page;

            return this.View(viewmodel);
        }

        [Authorize]
        public IActionResult ByUser(int id, int page = 1, string search = null)
        {
            var user = this.HttpContext.User.Identity.Name;

            var viewmodel = new PostAllModel();
            viewmodel.Posts = this.postsService.GetAll<PostViewModel>(search, ItemsPerPage, (page - 1) * ItemsPerPage, user);
            var count = this.postsService.GetCount(user);
            viewmodel.Search = search;
            viewmodel.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);

            if (viewmodel.PagesCount == 0)
            {
                viewmodel.PagesCount = 1;
            }

            viewmodel.CurrentPage = page;

            return this.View(viewmodel);
        }

        public IActionResult ById(int id)
        {
            var postViewModel = this.postsService.GetById<PostViewModel>(id);
            if (postViewModel == null)
            {
                return this.NotFound();
            }

            if (postViewModel.VotesCount < 0)
            {
                postViewModel.VotesCount = 0;
            }

            return this.View(postViewModel);
        }

        [Authorize]
        public IActionResult Create()
        {
            var categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            var viewModel = new PostCreateInputModel
            {
                Categories = categories,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(PostCreateInputModel input)
        {
            var post = AutoMapperConfig.MapperInstance.Map<PostCreateInputModel>(input);

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var files = input.Files;

            var postId = await this.postsService.CreateAsync(input.Title, input.Content, input.CategoryId, user.Id);

            if (files != null)
            {
                var urlOfProducts = await this.postsService.UploadAsync(this.cloudinary, files);
                await this.postsService.AddImageInBase(urlOfProducts, postId);
            }

            return this.RedirectToAction(nameof(this.ById), new { id = postId });
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var postViewModel = this.postsService.GetById<PostEditModel>(id);

            if (postViewModel == null)
            {
                return this.NotFound();
            }

            var categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            postViewModel.Categories = categories;
            var date = postViewModel.CreatedOn;

            postViewModel.CreatedOn = date;

            var postUserName = postViewModel.UserUserName;
            var currentUser = this.HttpContext.User.Identity.Name;

            if (postUserName != currentUser)
            {
                return this.BadRequest("Failed to edit the post");
            }

            return this.View(postViewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(PostEditModel input)
        {
            var post = AutoMapperConfig.MapperInstance.Map<Post>(input);

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var currentPost = this.postsService.GetById<PostEditModel>(input.Id);

            var user = await this.userManager.GetUserAsync(this.User);
            post.UserId = user.Id;
            post.CreatedOn = currentPost.CreatedOn;
            var postId = await this.postsService.Edit(post);
            return this.RedirectToAction(nameof(this.ById), new { id = postId });
        }

        [Authorize]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var post = this.postsService.GetById<PostDeleteModel>(id);

            var postUserName = post.UserUserName;
            var currentUser = this.HttpContext.User.Identity.Name;

            if (postUserName != currentUser)
            {
                return this.BadRequest("Failed to delete the post");
            }

            var postToDelete = AutoMapperConfig.MapperInstance.Map<PostDeleteModel>(post);
            return this.View(postToDelete);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(PostDeleteModel input)
        {
            var post = AutoMapperConfig.MapperInstance.Map<Post>(input);

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.postsService.Delete(post);

            return this.RedirectToAction("All");
        }

        [HttpPost]
        public async Task<IActionResult> Upload(ICollection<IFormFile> files)
        {
            var urlOfProducts = await this.postsService.UploadAsync(this.cloudinary, files);

            return this.Redirect("All");
        }
    }
}

Web/ForumSystem.Web/Views/Shared/_Layout.cshtml
@using ForumSystem.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.superhero.css" rel="stylesheet" asp-append-version="true" />
        <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.superhero.css" rel="stylesheet" asp-append-version="true" />
        <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-sm">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="https://www.communityfitness.com/wp-content/uploads/2019/05/CommunityFitnessLogo_orange.jpg" width="200" height="60" class="mr-auto" alt="logo"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="nav-link" data-toggle="dropdown" role="button" aria-expanded="false">Posts <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="dropdown-item">
                                    <a asp-area="" asp-controller="Posts" asp-action="All" style="color:azure">All Posts</a>
                                </li>
                                <li class="dropdown-item">
                                    <a asp-area="" asp-controller="Posts" asp-action="Create" style="color:azure">Create Post</a>
                                </li>
                                <li class="dropdown-item">
                                    <a asp-area="" asp-controller="Posts" asp-action="ByUser" style="color:azure">My Posts</a>
                                </li>
                            </ul>
                        <li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="All">Categories</a>
                        </li>
                        <form>
                            <p>
                                <input type="text" name="Search" />
                                <input type="submit" value="Search" asp-area="" asp-controller="Posts" asp-action="All" />
                            </p>
                        </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>

        <div class="text-dark">
            <aside class="col-md-3 magazine-page">
                <vc:sidebar></vc:sidebar>
            </aside>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>